[profile.default]
src = "contracts"
out = "out"
optimizer = true
optimizer_runs = 20000
solc_version = "0.8.27"
libs = ["lib"]
test = 'test'
cache_path = 'forge-cache'
fs_permissions = [{ access = "read", path = "./out"}]
evm_version = "cancun"
via_ir = true

[profile.dev]
src = "contracts"
out = "out"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.27"
libs = ["lib"]
test = 'test/foundry'
cache_path = 'forge-cache'
fs_permissions = [{ access = "read", path = "./out"}]
evm_version = "cancun"
via_ir = true

[fmt]
tab_width = 2

[profile.lint]
exclude_lints = [
    "unsafe-typecast",
    "unused-import",
    "erc20-unchecked-transfer",
    "mixed-case-variable",
    "unwrapped-modifier-logic",
    "mixed-case-function",
    "unaliased-plain-import",
    "asm-keccak256",
    "screaming-snake-case-const",
    "incorrect-shift",
    "screaming-snake-case-immutable",
    "unchecked-call",
    "pascal-case-struct",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
